spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Warehouse?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  mybatis plus:
    mapper-locations: classpath*:/mapper/**.xml
#    mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 8181
  servlet:
    context-path: /backEndWarehouse
  tomcat:
    uri-encoding: UTF-8
